const express = require('express');
const Quotation = require('../models/Quotation');
const authMiddleware = require('../middleware/auth');

const router = express.Router();

// gett all invoices generated by a user.
router.get('/', authMiddleware, async (req, res, next) => {
  const userId = req.user.id;

  try {
    const quotations = await Quotation.find({ userId });
    res.status(200).json(quotations);

  } catch (error) {
    next(error)
  }
});


module.exports = router;